In [1]:
import numpy as np

## 1

In [2]:
data_int = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
data_int

array([[52, 76,  9, 59,  3],
       [67, 71, 27, 22, 94],
       [88, 30, 40, 33, 22],
       [51, 27, 72, 72, 34],
       [98, 55, 11, 84, 81]])

## 2

In [3]:
min_val = np.min(data_int)
max_val = np.max(data_int)

data_norm = (data_int - min_val) / (max_val - min_val)
data_norm = np.round(data_norm, decimals=2)
data_norm

array([[0.52, 0.77, 0.06, 0.59, 0.  ],
       [0.67, 0.72, 0.25, 0.2 , 0.96],
       [0.89, 0.28, 0.39, 0.32, 0.2 ],
       [0.51, 0.25, 0.73, 0.73, 0.33],
       [1.  , 0.55, 0.08, 0.85, 0.82]])

## 3

In [4]:
mean_val = np.round(np.mean(data_int))
std_dev = np.std(data_int)

z_score_vector = (data_int - mean_val) / std_dev
z_score_vector

array([[ 0.03595667,  0.89891682, -1.51018026,  0.28765338, -1.7259203 ],
       [ 0.57530677,  0.71913346, -0.86296015, -1.04274351,  1.54613693],
       [ 1.33039689, -0.75509013, -0.3955234 , -0.64722011, -1.04274351],
       [ 0.        , -0.86296015,  0.75509013,  0.75509013, -0.61126344],
       [ 1.68996362,  0.14382669, -1.43826691,  1.1865702 ,  1.07870018]])

## 4

In [5]:
split_vector = np.ravel(data_int)
split_vector

array([52, 76,  9, 59,  3, 67, 71, 27, 22, 94, 88, 30, 40, 33, 22, 51, 27,
       72, 72, 34, 98, 55, 11, 84, 81])

## 5

In [6]:
vect1 = np.array(np.random.randint(1,10, size=5))
vect2 = np.array(np.random.randint(1,10, size=5))
dot_product = np.dot(vect1, vect2)
dot_product

105

## 6

In [8]:
data2 = np.array(np.random.randint(1, 100, size=9)).reshape(3,3)
data1 = data_int[0:3, 0:3]

multiplication_matrix = data1*data2
multiplication_matrix

array([[1196, 5396,   45],
       [2278, 2201, 1944],
       [8272, 1200,  400]])

In [9]:
np.dot(data1, data2)

array([[4626, 6408, 5822],
       [6493, 8038, 5717],
       [6804, 8778, 3000]])

## 7

In [10]:
indentify_matrix = np.identity(3)
martix = indentify_matrix*2
matrix = np.linalg.inv(martix)
martix

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

## 8

In [11]:
np.linalg.eig(data1)

EigResult(eigenvalues=array([152.31794212 +0.j        ,   5.34102894+16.19889923j,
         5.34102894-16.19889923j]), eigenvectors=array([[ 0.52502631+0.j        ,  0.36673112-0.23597214j,
         0.36673112+0.23597214j],
       [ 0.62455297+0.j        , -0.07196255+0.2230376j ,
        -0.07196255-0.2230376j ],
       [ 0.57817035+0.j        , -0.86885042+0.j        ,
        -0.86885042-0.j        ]]))

## 9

In [15]:
random_idx = np.random.choice(data_int.size, 5)
random_idx

array([15, 14,  4, 11, 23])

In [16]:
data_float = data_int.astype('float16')
data_float = data_float.reshape(25, )
data_float = data_float.ravel()

data_float[random_idx] = np.nan
data_float = data_float.reshape(5, 5)
data_float

array([[52., 76.,  9., 59., nan],
       [67., 71., 27., 22., 94.],
       [88., nan, 40., 33., nan],
       [nan, 27., 72., 72., 34.],
       [98., 55., 11., nan, 81.]], dtype=float16)

In [17]:
np.isnan( data_float)

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False,  True],
       [ True, False, False, False, False],
       [False, False, False,  True, False]])

In [18]:
np.argwhere(np.isnan(data_float))

array([[0, 4],
       [2, 1],
       [2, 4],
       [3, 0],
       [4, 3]], dtype=int64)

## 10

In [20]:
matrix_mean = np.nanmean(data_float)
matrix_mean

54.4

In [21]:
nan_idx = np.isnan(data_float)

data_float[nan_idx] = matrix_mean
data_float

array([[52. , 76. ,  9. , 59. , 54.4],
       [67. , 71. , 27. , 22. , 94. ],
       [88. , 54.4, 40. , 33. , 54.4],
       [54.4, 27. , 72. , 72. , 34. ],
       [98. , 55. , 11. , 54.4, 81. ]], dtype=float16)