## 1

In [1]:
import numpy as np

## 2

In [2]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3

In [28]:
arr2 = np.arange(0, 50)
arr_el_size = arr2.itemsize
arr_type = arr2[0].dtype
arr_size = arr2[0].itemsize * 50
print(f'"{arr_size}" is list size with element size = {arr_el_size} for items elements of {arr_type} ')

"200" is list size with element size = 4 for items elements of int32 


## 4

In [3]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

## 5

In [8]:
vector_arange = np.arange(10, 50)
vector_arange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 6

In [6]:
vector_arange[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 7

In [9]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 8

In [11]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4], dtype=int64),)

## 9

In [12]:
np.eye(3, k=1, dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## 10

In [13]:
y = np.zeros((5,5))
np.full_like(y, np.arange(0, 5, dtype=float))

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## 11

In [14]:
np.linspace(0,1,num=11, endpoint=False, dtype=float)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 12

In [15]:
np.sort(np.random.rand(10))

array([0.00716848, 0.07557269, 0.12749283, 0.24885355, 0.48820897,
       0.50567311, 0.53734563, 0.58327148, 0.91733012, 0.98842088])

## 13

In [16]:
list_type = ['int8', 'int32', 'int64', 'float32', 'float64']

for int_t in list_type[:3]:
    print(np.iinfo(int_t))

for float_t in list_type[3:]:
    print(np.finfo(float_t))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.40129

## 14

In [17]:
np.arange(10, dtype = 'float16').astype('float32', copy=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [18]:
np.arange(10, dtype='float16').astype('int32', copy=False)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 15

In [19]:
vector_mean = np.arange(9).reshape(3, 3)
np.mean(vector_mean, axis=1)

array([1., 4., 7.])

## 16

In [20]:
vector_2D_sort = np.random.randint(0, 10, (2, 3))
np.argsort(vector_2D_sort, axis=0)

array([[1, 0, 0],
       [0, 1, 1]], dtype=int64)

## 17

In [21]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 18

In [23]:
vector_repeat = np.repeat([0, 1, 2], [2, 3, 1])
vector_repeat

array([0, 0, 1, 1, 1, 2])

In [24]:
np.bincount(vector_repeat)

array([2, 3, 1], dtype=int64)